import { Medicine } from './types';

export const MEDICINES: Medicine[] = [
  {
    id: '1',
    name: 'Paracetamol 500mg',
    category: 'Tablets',
    price: 5.99,
    image: 'https://picsum.photos/400/400?random=1',
    shortDescription: 'Effective pain reliever and fever reducer.',
    description: 'Paracetamol is a common painkiller used to treat aches and pain. It can also be used to reduce a high temperature.',
    dosage: 'Adults: 1-2 tablets every 4-6 hours. Do not exceed 8 tablets in 24 hours.',
    inStock: true,
  },
  {
    id: '2',
    name: 'Amoxicillin 250mg',
    category: 'Capsules',
    price: 12.50,
    image: 'https://picsum.photos/400/400?random=2',
    shortDescription: 'Antibiotic for bacterial infections.',
    description: 'Amoxicillin is a penicillin antibiotic that fights bacteria. It is used to treat many different types of infection caused by bacteria.',
    dosage: 'Take one capsule every 8 hours as prescribed by your doctor.',
    inStock: true,
  },
  {
    id: '3',
    name: 'Cough Syrup Expectorant',
    category: 'Syrups',
    price: 8.99,
    image: 'https://picsum.photos/400/400?random=3',
    shortDescription: 'Relieves chest congestion.',
    description: 'Helps loosen phlegm (mucus) and thin bronchial secretions to drain bronchial tubes.',
    dosage: '10ml every 4 hours. Shake well before use.',
    inStock: true,
  },
  {
    id: '4',
    name: 'Ibuprofen 400mg',
    category: 'Tablets',
    price: 6.49,
    image: 'https://picsum.photos/400/400?random=4',
    shortDescription: 'Anti-inflammatory pain relief.',
    description: 'Ibuprofen is a nonsteroidal anti-inflammatory drug (NSAID). It works by reducing hormones that cause inflammation and pain in the body.',
    dosage: 'Take 1 tablet every 4 to 6 hours with food.',
    inStock: true,
  },
  {
    id: '5',
    name: 'Insulin Glargine',
    category: 'Injections',
    price: 45.00,
    image: 'https://picsum.photos/400/400?random=5',
    shortDescription: 'Long-acting insulin for diabetes.',
    description: 'Insulin glargine is a long-acting insulin that starts to work several hours after injection and keeps working evenly for 24 hours.',
    dosage: 'Inject subcutaneously once daily at the same time each day.',
    inStock: true,
  },
  {
    id: '6',
    name: 'Vitamin C 1000mg',
    category: 'Tablets',
    price: 9.99,
    image: 'https://picsum.photos/400/400?random=6',
    shortDescription: 'Immune system support supplement.',
    description: 'Vitamin C is an essential nutrient that supports the immune system and acts as an antioxidant.',
    dosage: 'Take one tablet daily dissolved in water.',
    inStock: true,
  },
  {
    id: '7',
    name: 'Hydrocortisone Cream 1%',
    category: 'Topical',
    price: 7.25,
    image: 'https://picsum.photos/400/400?random=7',
    shortDescription: 'Relieves skin irritation and itching.',
    description: 'Topical steroid used to treat inflammation of the skin caused by a number of conditions such as allergic reactions, eczema, or psoriasis.',
    dosage: 'Apply a thin layer to the affected area 2-3 times daily.',
    inStock: true,
  },
  {
    id: '8',
    name: 'Omeprazole 20mg',
    category: 'Capsules',
    price: 14.99,
    image: 'https://picsum.photos/400/400?random=8',
    shortDescription: 'Acid reflux and heartburn relief.',
    description: 'Omeprazole is a proton pump inhibitor that decreases the amount of acid produced in the stomach.',
    dosage: 'Take one capsule daily before a meal, preferably in the morning.',
    inStock: true,
  },
  {
    id: '9',
    name: 'Cetirizine 10mg',
    category: 'Tablets',
    price: 5.50,
    image: 'https://picsum.photos/400/400?random=9',
    shortDescription: 'Allergy relief (Antihistamine).',
    description: 'Cetirizine is an antihistamine used to relieve allergy symptoms such as watery eyes, runny nose, itching eyes/nose, and sneezing.',
    dosage: 'Take one tablet once daily.',
    inStock: true,
  },
  {
    id: '10',
    name: 'Multivitamin Complex',
    category: 'Tablets',
    price: 11.99,
    image: 'https://picsum.photos/400/400?random=10',
    shortDescription: 'Daily nutritional supplement.',
    description: 'Contains a blend of essential vitamins and minerals to support overall health and well-being.',
    dosage: 'Take one tablet daily with food.',
    inStock: true,
  },
  {
    id: '11',
    name: 'Diclofenac Gel',
    category: 'Topical',
    price: 8.50,
    image: 'https://picsum.photos/400/400?random=11',
    shortDescription: 'Topical pain relief for joints.',
    description: 'Nonsteroidal anti-inflammatory drug (NSAID) used to treat joint pain caused by osteoarthritis.',
    dosage: 'Apply to affected area 4 times daily.',
    inStock: true,
  },
  {
    id: '12',
    name: 'Saline Nasal Spray',
    category: 'Topical',
    price: 4.99,
    image: 'https://picsum.photos/400/400?random=12',
    shortDescription: 'Moisturizes dry nasal passages.',
    description: 'Provides relief from dry, irritated nasal passages caused by colds, allergies, or dry air.',
    dosage: '2 sprays in each nostril as needed.',
    inStock: true,
  },
];
